spring.application.name=ResourceManagementProject

spring.datasource.url=jdbc:postgresql://localhost:5432/DB_ResourceManagement
spring.datasource.username=postgres
spring.datasource.password=emna

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
